// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHitUdDI4wtSvWt6Fu_2vpZ0cgLy31bpY',
    appId: '1:390747502926:web:f907d06cc46a78e86fc61f',
    messagingSenderId: '390747502926',
    projectId: 'flutterdemo-69a78',
    authDomain: 'flutterdemo-69a78.firebaseapp.com',
    storageBucket: 'flutterdemo-69a78.appspot.com',
    measurementId: 'G-FZV26V6HYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jlTFtChUAvbEazMKJ2CshEX1JZtRis8',
    appId: '1:390747502926:android:70c45c894e19e6b96fc61f',
    messagingSenderId: '390747502926',
    projectId: 'flutterdemo-69a78',
    storageBucket: 'flutterdemo-69a78.appspot.com',
  );
}
