// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq_apAj9OL8T3RhcXGliAFanmMoaPHOKI',
    appId: '1:933529396560:web:cd9c89fa6a2a00c2ce7855',
    messagingSenderId: '933529396560',
    projectId: 'todoappdemo1-abd76',
    authDomain: 'todoappdemo1-abd76.firebaseapp.com',
    storageBucket: 'todoappdemo1-abd76.appspot.com',
    measurementId: 'G-0L42BGQ8D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw8pf-V99QbDO3WBUYQjVdIKOvw_VeRyk',
    appId: '1:933529396560:android:a2afae18acc33c7fce7855',
    messagingSenderId: '933529396560',
    projectId: 'todoappdemo1-abd76',
    storageBucket: 'todoappdemo1-abd76.appspot.com',
  );
}
